-- 027_seed_countries_extended.sql
-- Canonical-only incremental country seed to improve team/player ingestion coverage
-- outside WC2026 baseline. Keeps the same ISO-first contract from migration 003.

begin;

insert into countries (
  code_alpha2,
  code_alpha3,
  numeric_code,
  fifa_code,
  ioc_code,
  default_name,
  names,
  official_names,
  region,
  subregion,
  continent,
  timezone_default,
  timezones,
  currency_code,
  currency_name,
  flag_emoji,
  is_fifa_member,
  is_sovereign,
  payload
) values
('AE','ARE','784','UAE','UAE','Emiratos Arabes Unidos','{"es":"Emiratos Arabes Unidos","en":"United Arab Emirates"}','{"es":"Emiratos Arabes Unidos","en":"United Arab Emirates"}','Asia','Western Asia','AS','Asia/Dubai',array['Asia/Dubai'],'AED','UAE Dirham','🇦🇪',true,true,'{"sports":{"confederation":"AFC"},"aliases":["UAE","United Arab Emirates"]}'),
('AO','AGO','024','ANG','ANG','Angola','{"es":"Angola","en":"Angola"}','{"en":"Republic of Angola"}','Africa','Middle Africa','AF','Africa/Luanda',array['Africa/Luanda'],'AOA','Angolan Kwanza','🇦🇴',true,true,'{"sports":{"confederation":"CAF"}}'),
('AL','ALB','008','ALB','ALB','Albania','{"es":"Albania","en":"Albania"}','{"en":"Republic of Albania"}','Europe','Southern Europe','EU','Europe/Tirane',array['Europe/Tirane'],'ALL','Albanian Lek','🇦🇱',true,true,'{"sports":{"confederation":"UEFA"}}'),
('AM','ARM','051','ARM','ARM','Armenia','{"es":"Armenia","en":"Armenia"}','{"en":"Republic of Armenia"}','Asia','Western Asia','AS','Asia/Yerevan',array['Asia/Yerevan'],'AMD','Armenian Dram','🇦🇲',true,true,'{"sports":{"confederation":"UEFA"}}'),
('AZ','AZE','031','AZE','AZE','Azerbaiyan','{"es":"Azerbaiyan","en":"Azerbaijan"}','{"en":"Republic of Azerbaijan"}','Asia','Western Asia','AS','Asia/Baku',array['Asia/Baku'],'AZN','Azerbaijani Manat','🇦🇿',true,true,'{"sports":{"confederation":"UEFA"}}'),
('BG','BGR','100','BUL','BUL','Bulgaria','{"es":"Bulgaria","en":"Bulgaria"}','{"en":"Republic of Bulgaria"}','Europe','Eastern Europe','EU','Europe/Sofia',array['Europe/Sofia'],'BGN','Bulgarian Lev','🇧🇬',true,true,'{"sports":{"confederation":"UEFA"}}'),
('BJ','BEN','204','BEN','BEN','Benin','{"es":"Benin","en":"Benin"}','{"en":"Republic of Benin"}','Africa','Western Africa','AF','Africa/Porto-Novo',array['Africa/Porto-Novo'],'XOF','West African CFA Franc','🇧🇯',true,true,'{"sports":{"confederation":"CAF"}}'),
('BO','BOL','068','BOL','BOL','Bolivia','{"es":"Bolivia","en":"Bolivia"}','{"en":"Plurinational State of Bolivia"}','Americas','South America','SA','America/La_Paz',array['America/La_Paz'],'BOB','Boliviano','🇧🇴',true,true,'{"sports":{"confederation":"CONMEBOL"}}'),
('CM','CMR','120','CMR','CMR','Camerun','{"es":"Camerun","en":"Cameroon"}','{"en":"Republic of Cameroon"}','Africa','Middle Africa','AF','Africa/Douala',array['Africa/Douala'],'XAF','Central African CFA Franc','🇨🇲',true,true,'{"sports":{"confederation":"CAF"}}'),
('CR','CRI','188','CRC','CRC','Costa Rica','{"es":"Costa Rica","en":"Costa Rica"}','{"en":"Republic of Costa Rica"}','Americas','Central America','NA','America/Costa_Rica',array['America/Costa_Rica'],'CRC','Costa Rican Colon','🇨🇷',true,true,'{"sports":{"confederation":"CONCACAF"}}'),
('DK','DNK','208','DEN','DEN','Dinamarca','{"es":"Dinamarca","en":"Denmark"}','{"en":"Kingdom of Denmark"}','Europe','Northern Europe','EU','Europe/Copenhagen',array['Europe/Copenhagen'],'DKK','Danish Krone','🇩🇰',true,true,'{"sports":{"confederation":"UEFA"}}'),
('ET','ETH','231','ETH','ETH','Etiopia','{"es":"Etiopia","en":"Ethiopia"}','{"en":"Federal Democratic Republic of Ethiopia"}','Africa','Eastern Africa','AF','Africa/Addis_Ababa',array['Africa/Addis_Ababa'],'ETB','Ethiopian Birr','🇪🇹',true,true,'{"sports":{"confederation":"CAF"}}'),
('FI','FIN','246','FIN','FIN','Finlandia','{"es":"Finlandia","en":"Finland"}','{"en":"Republic of Finland"}','Europe','Northern Europe','EU','Europe/Helsinki',array['Europe/Helsinki'],'EUR','Euro','🇫🇮',true,true,'{"sports":{"confederation":"UEFA"}}'),
('GE','GEO','268','GEO','GEO','Georgia','{"es":"Georgia","en":"Georgia"}','{"en":"Georgia"}','Asia','Western Asia','AS','Asia/Tbilisi',array['Asia/Tbilisi'],'GEL','Georgian Lari','🇬🇪',true,true,'{"sports":{"confederation":"UEFA"}}'),
('GN','GIN','324','GUI','GUI','Guinea','{"es":"Guinea","en":"Guinea"}','{"en":"Republic of Guinea"}','Africa','Western Africa','AF','Africa/Conakry',array['Africa/Conakry'],'GNF','Guinean Franc','🇬🇳',true,true,'{"sports":{"confederation":"CAF"}}'),
('GR','GRC','300','GRE','GRE','Grecia','{"es":"Grecia","en":"Greece"}','{"en":"Hellenic Republic"}','Europe','Southern Europe','EU','Europe/Athens',array['Europe/Athens'],'EUR','Euro','🇬🇷',true,true,'{"sports":{"confederation":"UEFA"}}'),
('HN','HND','340','HON','HON','Honduras','{"es":"Honduras","en":"Honduras"}','{"en":"Republic of Honduras"}','Americas','Central America','NA','America/Tegucigalpa',array['America/Tegucigalpa'],'HNL','Honduran Lempira','🇭🇳',true,true,'{"sports":{"confederation":"CONCACAF"}}'),
('HU','HUN','348','HUN','HUN','Hungria','{"es":"Hungria","en":"Hungary"}','{"en":"Hungary"}','Europe','Central Europe','EU','Europe/Budapest',array['Europe/Budapest'],'HUF','Hungarian Forint','🇭🇺',true,true,'{"sports":{"confederation":"UEFA"}}'),
('IL','ISR','376','ISR','ISR','Israel','{"es":"Israel","en":"Israel"}','{"en":"State of Israel"}','Asia','Western Asia','AS','Asia/Jerusalem',array['Asia/Jerusalem'],'ILS','Israeli New Shekel','🇮🇱',true,true,'{"sports":{"confederation":"UEFA"}}'),
('IS','ISL','352','ISL','ISL','Islandia','{"es":"Islandia","en":"Iceland"}','{"en":"Iceland"}','Europe','Northern Europe','EU','Atlantic/Reykjavik',array['Atlantic/Reykjavik'],'ISK','Icelandic Krona','🇮🇸',true,true,'{"sports":{"confederation":"UEFA"}}'),
('JM','JAM','388','JAM','JAM','Jamaica','{"es":"Jamaica","en":"Jamaica"}','{"en":"Jamaica"}','Americas','Caribbean','NA','America/Jamaica',array['America/Jamaica'],'JMD','Jamaican Dollar','🇯🇲',true,true,'{"sports":{"confederation":"CONCACAF"}}'),
('KE','KEN','404','KEN','KEN','Kenia','{"es":"Kenia","en":"Kenya"}','{"en":"Republic of Kenya"}','Africa','Eastern Africa','AF','Africa/Nairobi',array['Africa/Nairobi'],'KES','Kenyan Shilling','🇰🇪',true,true,'{"sports":{"confederation":"CAF"}}'),
('KW','KWT','414','KUW','KUW','Kuwait','{"es":"Kuwait","en":"Kuwait"}','{"en":"State of Kuwait"}','Asia','Western Asia','AS','Asia/Kuwait',array['Asia/Kuwait'],'KWD','Kuwaiti Dinar','🇰🇼',true,true,'{"sports":{"confederation":"AFC"}}'),
('LB','LBN','422','LBN','LBN','Libano','{"es":"Libano","en":"Lebanon"}','{"en":"Lebanese Republic"}','Asia','Western Asia','AS','Asia/Beirut',array['Asia/Beirut'],'LBP','Lebanese Pound','🇱🇧',true,true,'{"sports":{"confederation":"AFC"}}'),
('LU','LUX','442','LUX','LUX','Luxemburgo','{"es":"Luxemburgo","en":"Luxembourg"}','{"en":"Grand Duchy of Luxembourg"}','Europe','Western Europe','EU','Europe/Luxembourg',array['Europe/Luxembourg'],'EUR','Euro','🇱🇺',true,true,'{"sports":{"confederation":"UEFA"}}'),
('LV','LVA','428','LVA','LAT','Letonia','{"es":"Letonia","en":"Latvia"}','{"en":"Republic of Latvia"}','Europe','Northern Europe','EU','Europe/Riga',array['Europe/Riga'],'EUR','Euro','🇱🇻',true,true,'{"sports":{"confederation":"UEFA"}}'),
('LY','LBY','434','LBY','LBA','Libia','{"es":"Libia","en":"Libya"}','{"en":"State of Libya"}','Africa','Northern Africa','AF','Africa/Tripoli',array['Africa/Tripoli'],'LYD','Libyan Dinar','🇱🇾',true,true,'{"sports":{"confederation":"CAF"}}'),
('MD','MDA','498','MDA','MDA','Moldavia','{"es":"Moldavia","en":"Moldova"}','{"en":"Republic of Moldova"}','Europe','Eastern Europe','EU','Europe/Chisinau',array['Europe/Chisinau'],'MDL','Moldovan Leu','🇲🇩',true,true,'{"sports":{"confederation":"UEFA"}}'),
('ME','MNE','499','MNE','MNE','Montenegro','{"es":"Montenegro","en":"Montenegro"}','{"en":"Montenegro"}','Europe','Southern Europe','EU','Europe/Podgorica',array['Europe/Podgorica'],'EUR','Euro','🇲🇪',true,true,'{"sports":{"confederation":"UEFA"}}'),
('MK','MKD','807','MKD','MKD','Macedonia del Norte','{"es":"Macedonia del Norte","en":"North Macedonia"}','{"en":"Republic of North Macedonia"}','Europe','Southern Europe','EU','Europe/Skopje',array['Europe/Skopje'],'MKD','Macedonian Denar','🇲🇰',true,true,'{"sports":{"confederation":"UEFA"},"aliases":["North Macedonia"]}'),
('ML','MLI','466','MLI','MLI','Mali','{"es":"Mali","en":"Mali"}','{"en":"Republic of Mali"}','Africa','Western Africa','AF','Africa/Bamako',array['Africa/Bamako'],'XOF','West African CFA Franc','🇲🇱',true,true,'{"sports":{"confederation":"CAF"}}'),
('MR','MRT','478','MTN','MTN','Mauritania','{"es":"Mauritania","en":"Mauritania"}','{"en":"Islamic Republic of Mauritania"}','Africa','Western Africa','AF','Africa/Nouakchott',array['Africa/Nouakchott'],'MRU','Mauritanian Ouguiya','🇲🇷',true,true,'{"sports":{"confederation":"CAF"}}'),
('NG','NGA','566','NGA','NGR','Nigeria','{"es":"Nigeria","en":"Nigeria"}','{"en":"Federal Republic of Nigeria"}','Africa','Western Africa','AF','Africa/Lagos',array['Africa/Lagos'],'NGN','Nigerian Naira','🇳🇬',true,true,'{"sports":{"confederation":"CAF"}}'),
('NI','NIC','558','NCA','NCA','Nicaragua','{"es":"Nicaragua","en":"Nicaragua"}','{"en":"Republic of Nicaragua"}','Americas','Central America','NA','America/Managua',array['America/Managua'],'NIO','Nicaraguan Cordoba','🇳🇮',true,true,'{"sports":{"confederation":"CONCACAF"}}'),
('OM','OMN','512','OMA','OMA','Oman','{"es":"Oman","en":"Oman"}','{"en":"Sultanate of Oman"}','Asia','Western Asia','AS','Asia/Muscat',array['Asia/Muscat'],'OMR','Omani Rial','🇴🇲',true,true,'{"sports":{"confederation":"AFC"}}'),
('PE','PER','604','PER','PER','Peru','{"es":"Peru","en":"Peru"}','{"en":"Republic of Peru"}','Americas','South America','SA','America/Lima',array['America/Lima'],'PEN','Peruvian Sol','🇵🇪',true,true,'{"sports":{"confederation":"CONMEBOL"}}'),
('PL','POL','616','POL','POL','Polonia','{"es":"Polonia","en":"Poland"}','{"en":"Republic of Poland"}','Europe','Eastern Europe','EU','Europe/Warsaw',array['Europe/Warsaw'],'PLN','Polish Zloty','🇵🇱',true,true,'{"sports":{"confederation":"UEFA"}}'),
('PS','PSE','275','PLE','PLE','Palestina','{"es":"Palestina","en":"Palestine"}','{"en":"State of Palestine"}','Asia','Western Asia','AS','Asia/Gaza',array['Asia/Gaza','Asia/Hebron'],'ILS','Israeli New Shekel','🇵🇸',true,false,'{"sports":{"confederation":"AFC"},"aliases":["Palestine"]}'),
('RO','ROU','642','ROU','ROU','Rumania','{"es":"Rumania","en":"Romania"}','{"en":"Romania"}','Europe','Eastern Europe','EU','Europe/Bucharest',array['Europe/Bucharest'],'RON','Romanian Leu','🇷🇴',true,true,'{"sports":{"confederation":"UEFA"}}'),
('RS','SRB','688','SRB','SRB','Serbia','{"es":"Serbia","en":"Serbia"}','{"en":"Republic of Serbia"}','Europe','Southern Europe','EU','Europe/Belgrade',array['Europe/Belgrade'],'RSD','Serbian Dinar','🇷🇸',true,true,'{"sports":{"confederation":"UEFA"}}'),
('SI','SVN','705','SVN','SLO','Eslovenia','{"es":"Eslovenia","en":"Slovenia"}','{"en":"Republic of Slovenia"}','Europe','Southern Europe','EU','Europe/Ljubljana',array['Europe/Ljubljana'],'EUR','Euro','🇸🇮',true,true,'{"sports":{"confederation":"UEFA"}}'),
('SK','SVK','703','SVK','SVK','Eslovaquia','{"es":"Eslovaquia","en":"Slovakia"}','{"en":"Slovak Republic"}','Europe','Central Europe','EU','Europe/Bratislava',array['Europe/Bratislava'],'EUR','Euro','🇸🇰',true,true,'{"sports":{"confederation":"UEFA"}}'),
('SV','SLV','222','SLV','ESA','El Salvador','{"es":"El Salvador","en":"El Salvador"}','{"en":"Republic of El Salvador"}','Americas','Central America','NA','America/El_Salvador',array['America/El_Salvador'],'USD','US Dollar','🇸🇻',true,true,'{"sports":{"confederation":"CONCACAF"}}'),
('SY','SYR','760','SYR','SYR','Siria','{"es":"Siria","en":"Syria"}','{"en":"Syrian Arab Republic"}','Asia','Western Asia','AS','Asia/Damascus',array['Asia/Damascus'],'SYP','Syrian Pound','🇸🇾',true,true,'{"sports":{"confederation":"AFC"}}'),
('TH','THA','764','THA','THA','Tailandia','{"es":"Tailandia","en":"Thailand"}','{"en":"Kingdom of Thailand"}','Asia','South-Eastern Asia','AS','Asia/Bangkok',array['Asia/Bangkok'],'THB','Thai Baht','🇹🇭',true,true,'{"sports":{"confederation":"AFC"}}'),
('TJ','TJK','762','TJK','TJK','Tayikistan','{"es":"Tayikistan","en":"Tajikistan"}','{"en":"Republic of Tajikistan"}','Asia','Central Asia','AS','Asia/Dushanbe',array['Asia/Dushanbe'],'TJS','Tajikistani Somoni','🇹🇯',true,true,'{"sports":{"confederation":"AFC"}}'),
('TM','TKM','795','TKM','TKM','Turkmenistan','{"es":"Turkmenistan","en":"Turkmenistan"}','{"en":"Turkmenistan"}','Asia','Central Asia','AS','Asia/Ashgabat',array['Asia/Ashgabat'],'TMT','Turkmenistan Manat','🇹🇲',true,true,'{"sports":{"confederation":"AFC"}}'),
('UA','UKR','804','UKR','UKR','Ucrania','{"es":"Ucrania","en":"Ukraine"}','{"en":"Ukraine"}','Europe','Eastern Europe','EU','Europe/Kyiv',array['Europe/Kyiv'],'UAH','Ukrainian Hryvnia','🇺🇦',true,true,'{"sports":{"confederation":"UEFA"}}'),
('UG','UGA','800','UGA','UGA','Uganda','{"es":"Uganda","en":"Uganda"}','{"en":"Republic of Uganda"}','Africa','Eastern Africa','AF','Africa/Kampala',array['Africa/Kampala'],'UGX','Ugandan Shilling','🇺🇬',true,true,'{"sports":{"confederation":"CAF"}}'),
('VE','VEN','862','VEN','VEN','Venezuela','{"es":"Venezuela","en":"Venezuela"}','{"en":"Bolivarian Republic of Venezuela"}','Americas','South America','SA','America/Caracas',array['America/Caracas'],'VES','Venezuelan Bolivar','🇻🇪',true,true,'{"sports":{"confederation":"CONMEBOL"}}'),
('VN','VNM','704','VIE','VIE','Vietnam','{"es":"Vietnam","en":"Vietnam"}','{"en":"Socialist Republic of Vietnam"}','Asia','South-Eastern Asia','AS','Asia/Ho_Chi_Minh',array['Asia/Ho_Chi_Minh'],'VND','Vietnamese Dong','🇻🇳',true,true,'{"sports":{"confederation":"AFC"}}'),
('XK','XKX','983','KOS',null,'Kosovo','{"es":"Kosovo","en":"Kosovo"}','{"en":"Republic of Kosovo"}','Europe','Southern Europe','EU','Europe/Belgrade',array['Europe/Belgrade'],'EUR','Euro','🇽🇰',true,false,'{"sports":{"confederation":"UEFA"},"iso_note":"User-assigned code widely used in football datasets"}')
on conflict (code_alpha2) do update set
  code_alpha3 = excluded.code_alpha3,
  numeric_code = excluded.numeric_code,
  fifa_code = excluded.fifa_code,
  ioc_code = excluded.ioc_code,
  default_name = excluded.default_name,
  names = excluded.names,
  official_names = excluded.official_names,
  region = excluded.region,
  subregion = excluded.subregion,
  continent = excluded.continent,
  timezone_default = excluded.timezone_default,
  timezones = excluded.timezones,
  currency_code = excluded.currency_code,
  currency_name = excluded.currency_name,
  flag_emoji = excluded.flag_emoji,
  is_fifa_member = excluded.is_fifa_member,
  is_sovereign = excluded.is_sovereign,
  payload = excluded.payload,
  updated_at = now();

commit;
